### ISSUE TITLE
ANAME fallback vs. override

### ISSUE THREAD

**Issue by Habbie** [each/draft-aname#25]
From face to face discussion at IETF 101, the correct behaviour is:
1. any A/AAAA record present next to the ANAME are fallbacks, not overrides, for the purpose of direct A/AAAA queries.
2. during outgoing XFR, the ANAME is always included. If there is A/AAAA next to it as well, whether we send that or do a fresh expansion, replacing those IPs, is an operator decision.

**Comment by matje** [comment]
Suggested text in PR #26

**Comment by matje** [comment]
Also this issue may duplicate #12

**Comment by fanf2** [comment]
In the revamped draft, the semantics are

* the sibling address records are modified in place

* they are stored in the zone so that they are available immediately at server startup

* they are transferred as usual for use by secondary servers

There's now no concept of configurable fallbacks or overrides. In effect the most recent successful substitution (in effect) acts as a fallback.

**Comment by matje** [comment]
TF: this is on the discuss branch because this is likely to lead to zombie address records - there's no way with the UPDATE semantics to tell the difference between fallback records and old records copied from the target.

The revamped draft deals with fallbacks or overrides a different way, but Tony rightfully points out the problem still exists. I think the argument of having possible zombie records should be addressed and thus there is need to define fallback address records.

I would like to see that existing sibling address records are considered fallback. *After* ANAME resolution there is no longer a concept of fallback and expanded address records that are at the same owner name as the ANAME should be used to serve the clients. If this happens before the zone is loaded in the primary name server, the expanded records are part of the zone and are used in zone transfers as well. If ANAME resolution happens after the zone is loaded, the expanded records are only used for handing out the response, and unexpanded records are kept in the zone and used in zone transfers.

**Comment by matje** [comment]
Closing this in favor of #58
