### ISSUE TITLE
split additional section processing

### ISSUE THREAD

**Issue by fanf2** [each/draft-aname#32]
As discussed with @matje in PR #31 it will probably be more clear to split additional section processing into separate recursive and authoritative sections - the "if the records are available" discussion is confusing and isn't justified by trying to make the text shorter

**Comment by matje** [comment]
@fanf2 would you be able to take a look at #59 ?

I split the additional section processing section up in two parts, then I removed any logic related to target address records when it comes to additional section processing in the authoritative server because in general the authoritative server should not need to know about target address records (the substitution is done before loading the zone, except if you are a stupid DNS trick provider).

If this looks good to you I will also notify the working group of this PR.
