### ISSUE TITLE
GeoIP

### ISSUE THREAD

**Issue by matje** [each/draft-aname#35]
> Regarding geoip, ANAME is no worse than manually configured address
> records, and it will eventually become better as resolver support is
> deployed. Geoip is the main reason for specifying (optional) ANAME support
> in resolvers. (I guess another reason might be to more faithfully respect
> the target address TTLs...) Resolver support isn't necessary, though,
> provided the ANAME target addresses work everywhere. So it might not be
> compatible with all existing geoip implementations, but I don't think
> that's a bug in ANAME.

Perhaps spend a word or two about how ANAME could interact with GeoIP but make clear that specifying the behavior with respect to GeoIP is out of scope.

**Comment by Habbie** [comment]
Also out of scope I suppose, but wanted to at least mention it: many websites only host a redirect to 'www' on their apex. Then 'www' could be a CNAME that benefits from all the niceties of having a CDN, while the apex at least resolves to IPs that are up right now, even if they're not the most nearby node. As that node only serves a redirect, this does not impact user experience a lot.

**Comment by vttale** [comment]
FWIW, what @Habbie describes is basically the way that Akamai's Toplevel Redirection service works (which is an earlier version of an additional feature they have called Zone Apex Mapping).  In toplevel redirection the auth serves addresses which get redirects based on the non-www host header to a www (or similar) name that has the full mapping capability.   Zone Apex Mapping doesn't need to do redirections because it has the secret sauce mapping data available to it.

**Comment by matje** [comment]
I added some words on GeoIP and tailored responses in the Alternative setup section in the Appendix in #52 (basically we leave it out of scope for the ANAME protocol, but provide some guidance on how to combine GeoIP with ANAME). If this is sufficient please +1, otherwise please provide text :)

**Comment by matje** [comment]
Closing this issue because of the text added in #52 - If you feel like the added text is insufficient feel free to reopen the issue and please provide text.
