### ISSUE TITLE
explain why CNAME at the parent isn't a solution to the problem

### ISSUE THREAD

**Issue by Habbie** [each/draft-aname#5]

**Comment by each** [comment]
Is the text in the introduction not sufficient for this?

It is common practice for websites to publish content at their registered
domain name (sometimes referred to as a "bare domain" or "zone apex": for
example, "example.com" rather than "www.example.com"). However,
[](#RFC1033) forbids the use of CNAME records at the same node as any
other record type. Zone apex nodes always contain SOA and NS RRsets,
and frequently contain other types such as DNSKEY, MX, TXT/SPF, etc.
Consequently, a CNAME record is not permitted at zone apex nodes.

**Comment by Habbie** [comment]
Yes, that looks like it should do.
